In [43]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("original array:", arr)

add_arr = arr + 2
print("after addition of 2:", add_arr)
mul_arr = arr * 3
print("after multiplying by 3:", mul_arr)
div_arr = arr / 2
print("after dividing by 2:", div_arr)


original array: [10 20 30 40 50]
after addition of 2: [12 22 32 42 52]
after multiplying by 3: [ 30  60  90 120 150]
after dividing by 2: [ 5. 10. 15. 20. 25.]


In [53]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("original array:", arr)
print("reversed array:", reversed_arr)


original array: [1 2 3 6 4 5]
reversed array: [5 4 6 3 2 1]


In [62]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_freq_x = values[np.argmax(counts)]
indices_x = np.where(x == most_freq_x)[0]
print("array x:", x)
print("frequent value:", most_freq_x)
print("indices:", indices_x)


array x: [1 2 3 4 5 1 2 1 1 1]
frequent value: 1
indices: [0 5 7 8 9]


In [70]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_freq_y = values[np.argmax(counts)]
indices_y = np.where(y == most_freq_y)[0]
print("array y:", y)
print("most frequent value:", most_freq_y)
print("indices:", indices_y)


array y: [1 1 1 2 3 4 2 4 3 3]
most frequent value: 1
indices: [0 1 2]


In [77]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2-D array:\n", arr)

element1 = arr[0, 1]
print("1st Row, 2nd column element:", element1)

element2 = arr[2, 0]
print("3rd Row, 1st column element:", element2)


2-D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
1st Row, 2nd column element: 20
3rd Row, 1st column element: 70


In [78]:
Vijaykiran = np.linspace(10, 100, 25)
print("Array Vijaykiran:", Vijaykiran)

print("Dimensions:", Vijaykiran.ndim)
print("Shape:", Vijaykiran.shape)
print("Total Elements:", Vijaykiran.size)
print("Data Type:", Vijaykiran.dtype)
print("Total Bytes:", Vijaykiran.nbytes)

transpose_reshape = Vijaykiran.reshape(25, 1)
print("Transpose using reshape():\n", transpose_reshape)


Array Vijaykiran: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Since `Vijaykiran` is a 1-D array, applying the `.T` attribute does not change it, as transpose has no effect on a 1-D array. It only works properly on arrays with 2 or more dimensions. To actually see a transpose-like effect using `.T`, the array first needs to be reshaped into a 2-D array.

In [83]:
print("using T attribute on 1-D array (no change):", Vijaykiran.T.shape)

Vijaykiran_2d = Vijaykiran.reshape(25, 1)
print("using T attribute on reshaped 2-D array:\n", Vijaykiran_2d.T)


using T attribute on 1-D array (no change): (25,)
using T attribute on reshaped 2-D array:
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [90]:
ucs420_Vijaykiran = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Array ucs420_Vijaykiran:\n", ucs420_Vijaykiran)

print("mean:", np.mean(ucs420_Vijaykiran))
print("median:", np.median(ucs420_Vijaykiran))
print("max:", np.max(ucs420_Vijaykiran))
print("Mmn:", np.min(ucs420_Vijaykiran))
print("Uuique elements:", np.unique(ucs420_Vijaykiran))


Array ucs420_Vijaykiran:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean: 43.333333333333336
median: 37.5
max: 90
Mmn: 10
Uuique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [91]:
reshaped_ucs420_Vijaykiran = ucs420_Vijaykiran.reshape(4, 3)
print("reshaped Array (4x3):\n", reshaped_ucs420_Vijaykiran)


reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [92]:
resized_ucs420_Vijaykiran = np.resize(ucs420_Vijaykiran, (2, 3))
print("resized Array (2x3):\n", resized_ucs420_Vijaykiran)


resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
