In [2]:
import numpy as np
A=np.array([[1,2,3]])
print(A)

[[1 2 3]]


In [5]:
arr=np.array([[[1,2,3],
               [4,5,6]],
              
              [[7,8,9],
               [10,11,12]]])
arr.size
arr.shape
             

(2, 2, 3)

In [6]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([10,20])
result=arr1+arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
## assingment-5


In [7]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

In [8]:
correct_temp=temperature+2
correct_temp

array([27, 30, 33, 37, 40, 29, 35, 42])

In [9]:
fahrenheit = (9/5) * temperature + 32
fahrenheit

array([ 77. ,  82.4,  87.8,  95. , 100.4,  80.6,  91.4, 104. ])

In [11]:
tempgreature_32=temperature[temperature>32]
tempgreature_32

array([35, 38, 33, 40])

In [12]:
count=np.sum(temperature>32)
count

np.int64(4)

Vectorization: Performs an operation on the entire NumPy array at once.

NumPy operations are generally faster because they use optimized internal implementations.

question2

In [13]:
steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]]) 

In [16]:
count=np.sum(steps)
count

np.int64(84200)

In [18]:
mean=np.mean(steps)
mean

np.float64(7016.666666666667)

In [20]:
median=np.median(steps)
median

np.float64(7300.0)

In [21]:
maximum=np.max(steps)
minimum=np.min(steps)
maximum

np.int64(9500)

In [22]:
minimum

np.int64(4500)

In [24]:
daily_steps=np.sum(steps,axis=0)
daily_steps

array([26500, 27300, 30400])

In [25]:
user_steps=np.sum(steps,axis=1)
user_steps

array([18300, 24500, 14400, 27000])

In [26]:
position = np.argmax(steps)
print(position)

11


In [27]:
position = np.unravel_index(np.argmax(steps), steps.shape)

print(position)

(np.int64(3), np.int64(2))


question-3

In [28]:
original = np.array([1, 2, 3, 4, 5, 6]) 

In [30]:
subset=original[1:5]
subset

array([2, 3, 4, 5])

In [31]:
subset[0]=999
original

array([  1, 999,   3,   4,   5,   6])

In [32]:
subset

array([999,   3,   4,   5])

In [33]:
copie_array = original[1:5].copy()

copie_array[0] = 500

In [34]:
copie_array

array([500,   3,   4,   5])

In [35]:
original

array([  1, 999,   3,   4,   5,   6])

In [36]:
arr1 = np.arange(1, 13).reshape(3, 4)

In [37]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr1[0]

array([1, 2, 3, 4])

In [39]:
arr1[-1]

array([ 9, 10, 11, 12])

In [41]:
arr1[:,1]

array([ 2,  6, 10])

In [43]:
arr1[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [44]:
flatten=arr1.flatten()
ravel=arr1.ravel()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
ravel[0]=999

In [47]:
arr1

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [48]:
ravel

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [49]:
ravel[0]=1
ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
flatten[0]=999
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
flatten

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [52]:
arr1.shape

(3, 4)

In [53]:
arr1.size

12

In [54]:
arr1.ndim

2

In [55]:
arr1.dtype

dtype('int64')

question-4

In [56]:
X = np.array([ [6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8] ]) 

In [57]:
y = np.array([40, 65, 30, 85]) 

In [58]:
X.shape

(4, 3)

In [59]:
X.ndim

2

In [60]:
XT = X.T
print(XT)

[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]


In [64]:
XTX = XT @ X
print(XTX)

[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]


(XTX)−1

In [65]:
inverse = np.linalg.inv(XT @ X)
inverse

array([[ 1.10521428, -0.09848746, -0.14581398],
       [-0.09848746,  0.00891203,  0.01190129],
       [-0.14581398,  0.01190129,  0.0368847 ]])

β=(XTX)−1XTy

In [66]:

beta = np.linalg.inv(X.T @ X) @ X.T @ y

print(beta)

[-0.15921454  0.14083853 10.06302242]


In [67]:
new_user = np.array([5, 40, 7])

predicte = new_user @ beta
predicte


np.float64(75.27862544778995)